import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
    const enterRoom = () => {
        // Enter Room Contract Logic
    }

    const refund = () => {
        // Refund Contract Logic
    }

    return (
        <div className="background">
            <Head>
                <title>Navigation - AptoStrike</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="header">
                <h1 className="header__title">Navigation</h1>
            </header>
            <main className='pageNav container'>
                <a className='btn btn--center btn--neon'>CONNECT WALLET</a>
                <a className='btn btn--center btn--neon'>DISCONNECT WALLET</a>
                <a className='btn btn--center btn--neon' onClick={() => enterRoom()}>Enter Room</a>
                <a className='btn btn--center btn--neon' onClick={() => refund()}>Refund</a>
                <Link href='/dashboard'>
                    <a className='btn btn--center btn--neon'>DASHBOARD</a>
                </Link>
            </main>
        </div>
    )
}
